### ISSUE TITLE
.

### ISSUE THREAD

**Issue by graysuit** [masterwok/libvlc-android-sdk#3]

**Comment by masterwok** [comment]
This is not currently supported by this library. [Media can only be set through a Uri at the moment.](https://github.com/masterwok/simple-vlc-player/blob/3020fc3c8abb382ee94d36460e891866922ba54b/simplevlcplayer/src/main/java/com/masterwok/simplevlcplayer/services/MediaPlayerService.kt#L544)

It should be possible since both are driven by libVLC. To support this, the libVLC version should/will probably have to be updated and expose an interface to add media as a stream. 

I'm unable to put time into this project at the moment but PRs are welcome.

**Comment by graysuit** [comment]
Sir thanks for replying,
<a href="https://github.com/ZeBobo5/Vlc.DotNet/blob/develop/src/Vlc.DotNet.Forms/VlcControl.cs#L208">Here</a> you can see, VLC.Net have used the stream and byte array using LibVLC,
Thats mean It can be possible in LibVLC,
No need to change all code,
Just please tell how can I use this same option in JAVA ?
